services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    
  Ang3\Component\Pdf\PdfFactory:
    arguments:
      $parameters: '%ang3_pdf.parameters%'

  ang3_pdf.factory:
    alias: Ang3\Component\Pdf\PdfFactory
    public: true