services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    
  Ang3\Component\Pdf\PdfFactory: ~

  ang3_pdf.factory:
    alias: Ang3\Component\Pdf\PdfFactory
    arguments:
      - '%ang3_pdf.parameters%'
    public: true